### YamlMime:YamlDocument
ms.openlocfilehash: f24a2ab1e4e4b87bb41b95b6ea5d80277c0e7094
ms.sourcegitcommit: b7e5bbbabc21df9fe93b4c18cc825920a0ab6fab
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 09/27/2018
ms.locfileid: "47409955"
documentType: LandingData
title: Документация по Ansible в Azure
metadata:
  title: 'Документация по Ansible в Azure: руководства, примеры, справочные материалы и ресурсы'
  description: Узнайте, как использовать Ansible для автоматизированной подготовки облачных решений, управления конфигурацией и развертывания приложений.
  ms.service: ansible
  keywords: ansible, azure, devops, tutorials, samples, reference
  author: tomarcher
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 08/27/2018
abstract:
  description: Используйте <a href="http://www.ansible.com">Ansible</a> для автоматизированной подготовки облачных решений, управления конфигурацией и развертывания приложений.
sections:
- title: 5-минутные руководства по началу работы
  items:
  - type: paragraph
    text: Установите и используйте Ansible для создания и администрирования виртуальных машин Linux в Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Установка Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Создание виртуальной машины Linux
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Управление виртуальной машиной Linux
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Пошаговые руководства
  items:
  - type: paragraph
    text: Узнайте, как создать и администрировать сетевую и вычислительную инфраструктуру и инфраструктуру хранилища в Azure с помощью Ansible.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Создание виртуальной машины Linux вместе с виртуальной сетью, общедоступным IP-адресом и виртуальным сетевым интерфейсом.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Запуск Ansible с помощью Bash в Azure Cloud Shell</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Создание динамического списка ресурсов Azure и управление им.</a>
    - html: <a href="./ansible-create-configure-vmss">Создание масштабируемых наборов виртуальных машин и управление ими в Azure.</a>
    - html: <a href="./ansible-deploy-app-vmss">Развертывание приложений в масштабируемых наборах виртуальных машин в Azure.</a>
    - html: <a href="./ansible-create-configure-aks">Создание кластеров Службы Azure Kubernetes и управление ими.</a>
    - html: <a href="./ansible-create-configure-application-gateway">Управление веб-трафиком с помощью Шлюза приложений Azure.</a>
- title: Справочные материалы
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Роли Playbook
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Выпуски и компоненты
      html: <p><a href="./ansible-matrix.md">Матрица модулей и ролей</a></p>
    - title: Средства
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Расширение Visual Studio Code для Ansible</a></p>
